# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fv_tracking/Diff.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Diff(genpy.Message):
  _md5sum = "555a2165453dfd975e2db54640de2933"
  _type = "fv_tracking/Diff"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x  #pix
float64 y
float64 velx
float64 vely
float64 Ix
float64 Iy
float64 recsize	#框选近大远小
float64 selectrec	#框选大小
"""
  __slots__ = ['x','y','velx','vely','Ix','Iy','recsize','selectrec']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,velx,vely,Ix,Iy,recsize,selectrec

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Diff, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.velx is None:
        self.velx = 0.
      if self.vely is None:
        self.vely = 0.
      if self.Ix is None:
        self.Ix = 0.
      if self.Iy is None:
        self.Iy = 0.
      if self.recsize is None:
        self.recsize = 0.
      if self.selectrec is None:
        self.selectrec = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.velx = 0.
      self.vely = 0.
      self.Ix = 0.
      self.Iy = 0.
      self.recsize = 0.
      self.selectrec = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.x, _x.y, _x.velx, _x.vely, _x.Ix, _x.Iy, _x.recsize, _x.selectrec))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.x, _x.y, _x.velx, _x.vely, _x.Ix, _x.Iy, _x.recsize, _x.selectrec,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.x, _x.y, _x.velx, _x.vely, _x.Ix, _x.Iy, _x.recsize, _x.selectrec))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.x, _x.y, _x.velx, _x.vely, _x.Ix, _x.Iy, _x.recsize, _x.selectrec,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
